//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using CapaEntidad;
    public partial class documentobdEntities1 : DbContext
    {
        public documentobdEntities1()
            : base("name=documentobdEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DEPARTAMENTO> DEPARTAMENTOes { get; set; }
        public virtual DbSet<DOCUMENTO> DOCUMENTOS { get; set; }
        public virtual DbSet<USUARIO> USUARIOS { get; set; }
    
        public virtual ObjectResult<docu_destino_Result> docu_destino(string departadestino)
        {
            var departadestinoParameter = departadestino != null ?
                new ObjectParameter("departadestino", departadestino) :
                new ObjectParameter("departadestino", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<docu_destino_Result>("docu_destino", departadestinoParameter);
        }
    
        public virtual ObjectResult<docu_empleado_Result> docu_empleado(string empleado)
        {
            var empleadoParameter = empleado != null ?
                new ObjectParameter("empleado", empleado) :
                new ObjectParameter("empleado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<docu_empleado_Result>("docu_empleado", empleadoParameter);
        }
    
        public virtual ObjectResult<docu_fecha_Result> docu_fecha(string fechaini, string fechafi)
        {
            var fechainiParameter = fechaini != null ?
                new ObjectParameter("fechaini", fechaini) :
                new ObjectParameter("fechaini", typeof(string));
    
            var fechafiParameter = fechafi != null ?
                new ObjectParameter("fechafi", fechafi) :
                new ObjectParameter("fechafi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<docu_fecha_Result>("docu_fecha", fechainiParameter, fechafiParameter);
        }
    
        public virtual ObjectResult<docu_origen_Result> docu_origen(string departaorigen)
        {
            var departaorigenParameter = departaorigen != null ?
                new ObjectParameter("departaorigen", departaorigen) :
                new ObjectParameter("departaorigen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<docu_origen_Result>("docu_origen", departaorigenParameter);
        }
    }
}
